### ISSUE TITLE
DHS does not reconnect to dcss if socket is broken

### ISSUE THREAD

**Issue by dsclassen** [tetrahedron-technologies/pydhsfw#91]
If DCSS is stopped or restarted loopDHS cannot reconnect.

```
2020-10-20 10:19:06,884 SPRYER urllib3.connectionpool-[_new_conn():230] DEBUG Starting new HTTP connection (1): localhost:5000
2020-10-20 10:19:07,212 SPRYER urllib3.connectionpool-[_make_request():442] DEBUG http://localhost:5000 "POST /v1/models/default:predict HTTP/1.1" 200 5481
2020-10-20 10:19:07,214 SPRYER pydhsfw.connection-[run():109] DEBUG Received unpacked raw message, <Response [200]>
2020-10-20 10:19:07,214 SPRYER pydhsfw.connection-[run():112] DEBUG Received factory created message: automl_predict_response
2020-10-20 10:19:07,214 SPRYER pydhsfw.processors-[run():95] DEBUG Processing message: automl_predict_response
2020-10-20 10:19:07,215 SPRYER loopDHS.py-[automl_predict_response():476] DEBUG Active operations pre-completed=[<pydhsfw.dcss.DcssActiveOperation object at 0x7f8e4825d110>]
2020-10-20 10:19:07,216 SPRYER loopDHS.py-[automl_predict_response():481] WARNING TOP AUTOML SCORE IS BELOW 0.50 THRESHOLD: 0.0956181
2020-10-20 10:19:07,222 SPRYER loopDHS.py-[automl_predict_response():521] INFO SEND TO DCSS: 0.51619 0.50429
2020-10-20 10:19:07,222 SPRYER loopDHS.py-[automl_predict_response():572] DEBUG Active operations post-completed=[]
2020-10-20 10:19:07,222 SPRYER pydhsfw.dcss-[write_msg():989] DEBUG Sending packed raw message version 2: b'          64            0 htos_operation_completed getLoopTip 3.9 failed 0.51619 0.50429 \x00'
2020-10-20 10:19:17,782 SPRYER pydhsfw.transport-[receive():186] WARNING Connection lost, attempting to reconnect
2020-10-20 10:19:17,782 SPRYER pydhsfw.tcpip-[_set_state():186] INFO Connection state: TransportState.DISCONNECTING, url: dcss://localhost:14242
2020-10-20 10:19:17,783 SPRYER pydhsfw.tcpip-[run():166] ERROR None
Traceback (most recent call last):
  File "/Users/classen/Documents/DCSS-STUFF/pydhsfw/pydhsfw/tcpip.py", line 156, in run
    self._reconnect()
  File "/Users/classen/Documents/DCSS-STUFF/pydhsfw/pydhsfw/tcpip.py", line 261, in _reconnect
    self._disconnect()
  File "/Users/classen/Documents/DCSS-STUFF/pydhsfw/pydhsfw/tcpip.py", line 250, in _disconnect
    sock.shutdown(socket.SHUT_RDWR)
OSError: [Errno 57] Socket is not connected
2020-10-20 10:19:17,785 SPRYER pydhsfw.tcpip-[_disconnect():254] DEBUG Not connected, ignoring disconnect request
```

**Comment by dsclassen** [comment]
The http code has a "heartbeat" that is used to monitor resources and if things go awry a `reconnect` function is called. What is our strategy for reconnecting to dcss?

**Comment by dsclassen** [comment]
Seems to be bonking in `tcpip.py` `_disconnect` function.

I guess it is difficult to disconnect a socket that is not connected.

<img width="898" alt="Screen Shot 2020-10-21 at 10 27 03 AM" src="https://user-images.githubusercontent.com/8882563/96755880-20b2c980-1388-11eb-9306-7bdce899fcdd.png">
